services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5076:5076"
    env_file:
      - ./server/server/secrets/.env
    entrypoint: ["dotnet", "server.dll"]
    