services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5076:5076"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    entrypoint: ["dotnet", "server.dll"]
    