services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5076:5076"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SSH_USER: ${SSH_USER}
      SSH_HOST: ${SSH_HOST}
      SSH_PORT: ${SSH_PORT}
    env_file:
      - .env
    entrypoint: ["dotnet", "server.dll"]
    