name: "Report Coverage"
on:
  workflow_run:
    workflows: ["Test and Coverage Report"]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      
      - name: "Download Coverage Artifacts"
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          json-summary-path: './coverage/coverage-summary.json'
          json-final-path: './coverage/coverage-final.json'
          comment-on: "pr"